-- MySQL Script generated by MySQL Workbench
-- Mon Jul 26 18:04:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vétérinaire
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Vétérinaire` ;

-- -----------------------------------------------------
-- Schema Vétérinaire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vétérinaire` DEFAULT CHARACTER SET utf8 ;
USE `Vétérinaire` ;

-- -----------------------------------------------------
-- Table `Vétérinaire`.`Propriétaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Propriétaire` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Propriétaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `rue` VARCHAR(255) NULL,
  `Propriétairecol` VARCHAR(45) NULL,
  `codepostal` INT(5) NULL,
  `ville` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `telephoneMobile` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Animal` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `DateNaissance` DATETIME NULL,
  `DateDeces` DATETIME NULL,
  `idPropriétaire` INT NOT NULL,
  PRIMARY KEY (`id`, `idPropriétaire`),
  INDEX `fk_Animal_Propriétaire1_idx` (`idPropriétaire` ASC),
  CONSTRAINT `fk_Animal_Propriétaire1`
    FOREIGN KEY (`idPropriétaire`)
    REFERENCES `Vétérinaire`.`Propriétaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Race_chien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Race_chien` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Race_chien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Chien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Chien` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Chien` (
  `idAnimal` INT NOT NULL,
  `taille` FLOAT NULL,
  `poids` FLOAT NULL,
  `idRace` INT NULL,
  INDEX `fk_Chien_Race_chien1_idx` (`idRace` ASC),
  PRIMARY KEY (`idAnimal`),
  CONSTRAINT `fk_Chien_Animal1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Vétérinaire`.`Animal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Chien_Race_chien1`
    FOREIGN KEY (`idRace`)
    REFERENCES `Vétérinaire`.`Race_chien` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Race_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Race_chat` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Race_chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Chat` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Chat` (
  `idAnimal` INT NOT NULL,
  `idRace` INT NULL,
  INDEX `fk_Chat_Race_chat1_idx` (`idRace` ASC),
  PRIMARY KEY (`idAnimal`),
  CONSTRAINT `fk_Chat_Animal`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Vétérinaire`.`Animal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Chat_Race_chat1`
    FOREIGN KEY (`idRace`)
    REFERENCES `Vétérinaire`.`Race_chat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Dossier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Dossier` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Dossier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `antecedents` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Veterinaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Veterinaire` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Veterinaire` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prénom` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `telephoneMobile` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Visite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Visite` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Visite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateVisite` DATETIME NULL,
  `heureVisite` DATETIME NULL,
  `raison` VARCHAR(45) NULL,
  `idDossier` INT NOT NULL,
  `idAnimal` INT NOT NULL,
  `idVeterinaire` INT NOT NULL,
  PRIMARY KEY (`id`, `idVeterinaire`, `idAnimal`, `idDossier`),
  INDEX `fk_Visite_Dossier1_idx` (`idDossier` ASC),
  INDEX `fk_Visite_Animal1_idx` (`idAnimal` ASC),
  INDEX `fk_Visite_Veterinaire1_idx` (`idVeterinaire` ASC),
  CONSTRAINT `fk_Visite_Dossier1`
    FOREIGN KEY (`idDossier`)
    REFERENCES `Vétérinaire`.`Dossier` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Visite_Animal1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `Vétérinaire`.`Animal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Visite_Veterinaire1`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Vétérinaire`.`Veterinaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Medicament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Medicament` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Medicament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `dosage` VARCHAR(45) NULL,
  `indications` VARCHAR(100) NULL,
  `effetsSecondaires` VARCHAR(100) NULL,
  `laboratoire` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Prescrire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Prescrire` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Prescrire` (
  `idVisite` INT NOT NULL,
  `idMedicament` INT NOT NULL,
  `posologie` VARCHAR(100) NULL,
  INDEX `fk_Prescrire_Visite1_idx` (`idVisite` ASC),
  PRIMARY KEY (`idVisite`, `idMedicament`),
  INDEX `fk_Prescrire_Medicament1_idx` (`idMedicament` ASC),
  CONSTRAINT `fk_Prescrire_Visite1`
    FOREIGN KEY (`idVisite`)
    REFERENCES `Vétérinaire`.`Visite` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prescrire_Medicament1`
    FOREIGN KEY (`idMedicament`)
    REFERENCES `Vétérinaire`.`Medicament` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Horaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Horaire` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Horaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jour` DATE NULL,
  `heureDebut` TIME NULL,
  `heureFin` TIME NULL,
  `idVeterinaire` INT NOT NULL,
  PRIMARY KEY (`id`, `idVeterinaire`),
  INDEX `fk_Horaire_Veterinaire1_idx` (`idVeterinaire` ASC),
  CONSTRAINT `fk_Horaire_Veterinaire1`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Vétérinaire`.`Veterinaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Effectuer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Effectuer` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Effectuer` (
  `idGarde` INT NOT NULL AUTO_INCREMENT,
  `idVeterinaire` INT NOT NULL,
  PRIMARY KEY (`idGarde`, `idVeterinaire`),
  INDEX `fk_Effectuer_Veterinaire1_idx` (`idVeterinaire` ASC),
  CONSTRAINT `fk_Effectuer_Veterinaire1`
    FOREIGN KEY (`idVeterinaire`)
    REFERENCES `Vétérinaire`.`Veterinaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vétérinaire`.`Garde`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vétérinaire`.`Garde` ;

CREATE TABLE IF NOT EXISTS `Vétérinaire`.`Garde` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `heure_debut` TIME NULL,
  `heure_fin` TIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Garde_Effectuer1`
    FOREIGN KEY (`id`)
    REFERENCES `Vétérinaire`.`Effectuer` (`idGarde`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
